/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Vikasitha
 */
public class AppointmentDetails extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentDetails
     */
    public AppointmentDetails() {
        initComponents();
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental3.jpg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel15.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private void clearDetails() {

    lblAppointmentNumber.setText("-");
    lblPatient.setText("-");
    lblAddress.setText("-");
    lblContact.setText("-");
    lblDentist.setText("-");
    lblTreatment.setText("-");
    lblDate.setText("-");
    lblTime.setText("-");
    lblStatus.setText("-");
    lblConsultation.setText("-");
    lblTreatmentCost.setText("-");
    lblTotal.setText("-");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchAppointment = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblAppointmentNumber = new javax.swing.JTextField();
        lblPatient = new javax.swing.JTextField();
        lblAddress = new javax.swing.JTextField();
        lblContact = new javax.swing.JTextField();
        lblDentist = new javax.swing.JTextField();
        lblTreatment = new javax.swing.JTextField();
        lblDate = new javax.swing.JTextField();
        lblTime = new javax.swing.JTextField();
        lblStatus = new javax.swing.JTextField();
        lblConsultation = new javax.swing.JTextField();
        lblTreatmentCost = new javax.swing.JTextField();
        lblTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointment Details");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Appointment Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 49, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Appointment Number :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 104, 222, -1));

        txtSearchAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSearchAppointment.setForeground(new java.awt.Color(51, 0, 204));
        getContentPane().add(txtSearchAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 147, 274, -1));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(204, 0, 0));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 147, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Appointment No :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 192, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 226, 170, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 260, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact Number :  ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 294, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dentist :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 328, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Treatment :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 362, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 396, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Time : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 430, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Status :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 464, 170, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Consultation Fee :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 498, 170, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Treatment Cost :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 532, 170, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Amount :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 566, 170, -1));

        lblAppointmentNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAppointmentNumber.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblAppointmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 192, 278, -1));

        lblPatient.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPatient.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 226, 278, -1));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 260, 278, -1));

        lblContact.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContact.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 294, 278, -1));

        lblDentist.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDentist.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 328, 278, -1));

        lblTreatment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTreatment.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 362, 278, -1));

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDate.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 396, 278, -1));

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTime.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 430, 278, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 464, 278, -1));

        lblConsultation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsultation.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblConsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 498, 278, -1));

        lblTreatmentCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTreatmentCost.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblTreatmentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 532, 278, -1));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 566, 278, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental3.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String appointmentNumber =
            txtSearchAppointment.getText().trim();

    if (appointmentNumber.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter an appointment number.",
                "Search",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtSearchAppointment.requestFocus();

        return;
    }

    dao.AppointmentDAO appointmentDAO =
            new dao.AppointmentDAO();

    try {

        java.sql.ResultSet rs =
                appointmentDAO.searchAppointment(
                        appointmentNumber
                );

        if (rs != null && rs.next()) {

            lblAppointmentNumber.setText(
                    rs.getString("appointment_number")
            );

            lblPatient.setText(
                    rs.getString("patient_name")
            );

            lblAddress.setText(
                    rs.getString("address")
            );

            lblContact.setText(
                    rs.getString("contact_number")
            );

            lblDentist.setText(
                    rs.getString("dentist_name")
            );

            lblTreatment.setText(
                    rs.getString("treatment_name")
            );

            lblDate.setText(
                    rs.getString("appointment_date")
            );

            lblTime.setText(
                    rs.getString("appointment_time")
            );

            lblStatus.setText(
                    rs.getString("status")
            );

            lblConsultation.setText(
                    String.format(
                            "Rs. %.2f",
                            rs.getDouble("consultation_fee")
                    )
            );

            lblTreatmentCost.setText(
                    String.format(
                            "Rs. %.2f",
                            rs.getDouble("treatment_cost")
                    )
            );

            lblTotal.setText(
                    String.format(
                            "Rs. %.2f",
                            rs.getDouble("total_amount")
                    )
            );

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No appointment found for:\n"
                    + appointmentNumber,
                    "Appointment Not Found",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            clearDetails();
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error while searching appointment:\n"
                + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lblAddress;
    private javax.swing.JTextField lblAppointmentNumber;
    private javax.swing.JTextField lblConsultation;
    private javax.swing.JTextField lblContact;
    private javax.swing.JTextField lblDate;
    private javax.swing.JTextField lblDentist;
    private javax.swing.JTextField lblPatient;
    private javax.swing.JTextField lblStatus;
    private javax.swing.JTextField lblTime;
    private javax.swing.JTextField lblTotal;
    private javax.swing.JTextField lblTreatment;
    private javax.swing.JTextField lblTreatmentCost;
    private javax.swing.JTextField txtSearchAppointment;
    // End of variables declaration//GEN-END:variables
}
