/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vikasitha
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        loadUserDetails();
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental4.jpg"));
        Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
        jLabel4.setIcon(new ImageIcon(scaledImage));
    
        setResizable(false);
        pack();
        setLocationRelativeTo(null);
    }
    
    private void loadUserDetails() {

    if (util.Session.isLoggedIn()) {

        model.User user = util.Session.getCurrentUser();

        lblWelcome.setText(
                "Welcome, " + user.getUsername()
                + " | Role: " + user.getRole()
        );

    } else {

        lblWelcome.setText("No user logged in.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnNewAppointment = new javax.swing.JButton();
        btnSearchAppointment = new javax.swing.JButton();
        btnPatients = new javax.swing.JButton();
        btnBilling = new javax.swing.JButton();
        btnDentists = new javax.swing.JButton();
        btnTreatments = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("SUNRISE DENTAL CLINIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 22, 436, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Appointment & Patient Management System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 76, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("lblWelcome");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnNewAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNewAppointment.setForeground(new java.awt.Color(0, 153, 255));
        btnNewAppointment.setText("New Appointment");
        btnNewAppointment.setMaximumSize(new java.awt.Dimension(100, 20));
        btnNewAppointment.setPreferredSize(new java.awt.Dimension(100, 20));
        btnNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 310, 50));

        btnSearchAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchAppointment.setForeground(new java.awt.Color(0, 153, 255));
        btnSearchAppointment.setText("Search Appointment");
        btnSearchAppointment.setMaximumSize(new java.awt.Dimension(100, 20));
        btnSearchAppointment.setPreferredSize(new java.awt.Dimension(100, 20));
        btnSearchAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 310, 50));

        btnPatients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPatients.setForeground(new java.awt.Color(0, 153, 255));
        btnPatients.setText("Patients");
        btnPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientsActionPerformed(evt);
            }
        });
        getContentPane().add(btnPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 310, 50));

        btnBilling.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBilling.setForeground(new java.awt.Color(0, 153, 255));
        btnBilling.setText("Billing");
        btnBilling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingActionPerformed(evt);
            }
        });
        getContentPane().add(btnBilling, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 310, 50));

        btnDentists.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDentists.setForeground(new java.awt.Color(0, 153, 255));
        btnDentists.setText("Dentists");
        btnDentists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDentistsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDentists, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 310, 50));

        btnTreatments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTreatments.setForeground(new java.awt.Color(0, 153, 255));
        btnTreatments.setText("Treatments");
        btnTreatments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreatmentsActionPerformed(evt);
            }
        });
        getContentPane().add(btnTreatments, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 310, 50));
        btnTreatments.getAccessibleContext().setAccessibleDescription("");

        btnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReports.setForeground(new java.awt.Color(0, 153, 255));
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 310, 50));

        btnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHelp.setForeground(new java.awt.Color(0, 153, 255));
        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(btnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 310, 50));
        btnHelp.getAccessibleContext().setAccessibleDescription("");

        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255)));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, 210, 40));

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 204, 255), new java.awt.Color(0, 204, 255)));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 210, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental4.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
           int answer = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (answer == javax.swing.JOptionPane.YES_OPTION) {

        util.Session.logout();

        Login login = new Login();

        login.setVisible(true);

        this.dispose();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
            int answer = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to exit the system?",
            "Exit System",
            javax.swing.JOptionPane.YES_NO_OPTION
    );

    if (answer == javax.swing.JOptionPane.YES_OPTION) {

        System.exit(0);
    }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientsActionPerformed
        // TODO add your handling code here:
    PatientManagement patientManagement =
            new PatientManagement();

    patientManagement.setVisible(true);
    }//GEN-LAST:event_btnPatientsActionPerformed

    private void btnNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppointmentActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Appointment Registration module will be opened here."
);
    }//GEN-LAST:event_btnNewAppointmentActionPerformed

    private void btnSearchAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAppointmentActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Appointment Search module will be opened here."
);
    }//GEN-LAST:event_btnSearchAppointmentActionPerformed

    private void btnBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Billing module will be opened here."
);
    }//GEN-LAST:event_btnBillingActionPerformed

    private void btnDentistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDentistsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Dentist Management module will be opened here."
);
    }//GEN-LAST:event_btnDentistsActionPerformed

    private void btnTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Treatment Management module will be opened here."
);
    }//GEN-LAST:event_btnTreatmentsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Reports module will be opened here."
);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(
        this,
        "Help module will be opened here."
);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilling;
    private javax.swing.JButton btnDentists;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnPatients;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSearchAppointment;
    private javax.swing.JButton btnTreatments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
