/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Vikasitha
 */
public class DentistManagement extends javax.swing.JFrame {

    /**
     * Creates new form DentistManagement
     */
    public DentistManagement() {
        initComponents();
        loadDentists();
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental9.jpeg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel5.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private void loadDentists() {

    dao.DentistDAO dentistDAO =
            new dao.DentistDAO();

    java.util.List<model.Dentist> dentists =
            dentistDAO.getAllDentistsList();

    javax.swing.table.DefaultTableModel tableModel =
            (javax.swing.table.DefaultTableModel)
                    tblDentists.getModel();

    tableModel.setRowCount(0);

    for (model.Dentist dentist : dentists) {

        tableModel.addRow(new Object[]{
            dentist.getDentistId(),
            dentist.getDentistName(),
            dentist.getSpecialization(),
            dentist.getStatus()
        });
    }
}
    
    private void clearForm() {

    txtDentistName.setText("");
    txtSpecialization.setText("");
    cmbStatus.setSelectedIndex(0);

    txtDentistName.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDentistName = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDentists = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dentist Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Dentist Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Dentist Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 126, 141, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Specialization :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 164, 141, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Status :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 223, 141, -1));

        txtDentistName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtDentistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 123, 353, -1));

        txtSpecialization.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 161, 353, -1));

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(51, 51, 255));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 353, -1));

        btnSave.setBackground(new java.awt.Color(153, 255, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(153, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        tblDentists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Dentist Name", "Specialization", "Status"
            }
        ));
        tblDentists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDentistsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDentists);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 340, 906, 235));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental9.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String name =
            txtDentistName.getText().trim();

    String specialization =
            txtSpecialization.getText().trim();

    String status =
            cmbStatus.getSelectedItem().toString();

    if (name.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the dentist name.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtDentistName.requestFocus();
        return;
    }

    model.Dentist dentist =
            new model.Dentist();

    dentist.setDentistName(name);
    dentist.setSpecialization(specialization);
    dentist.setStatus(status);

    dao.DentistDAO dentistDAO =
            new dao.DentistDAO();

    if (dentistDAO.addDentist(dentist)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Dentist added successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
        loadDentists();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to add dentist.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
            clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblDentistsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDentistsMouseClicked
        // TODO add your handling code here:
            int row = tblDentists.getSelectedRow();

    if (row >= 0) {

        txtDentistName.setText(
                tblDentists.getValueAt(row, 1).toString()
        );

        txtSpecialization.setText(
                tblDentists.getValueAt(row, 2).toString()
        );

        cmbStatus.setSelectedItem(
                tblDentists.getValueAt(row, 3).toString()
        );
    }
    }//GEN-LAST:event_tblDentistsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            int row = tblDentists.getSelectedRow();

    if (row == -1) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select a dentist from the table.",
                "Selection Required",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int dentistId =
            Integer.parseInt(
                    tblDentists.getValueAt(row, 0).toString()
            );

    String name =
            txtDentistName.getText().trim();

    String specialization =
            txtSpecialization.getText().trim();

    String status =
            cmbStatus.getSelectedItem().toString();

    if (name.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Dentist name cannot be empty.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    model.Dentist dentist =
            new model.Dentist();

    dentist.setDentistId(dentistId);
    dentist.setDentistName(name);
    dentist.setSpecialization(specialization);
    dentist.setStatus(status);

    dao.DentistDAO dentistDAO =
            new dao.DentistDAO();

    if (dentistDAO.updateDentist(dentist)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Dentist updated successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
        loadDentists();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to update dentist.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DentistManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DentistManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DentistManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DentistManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DentistManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDentists;
    private javax.swing.JTextField txtDentistName;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
