/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Vikasitha
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new form Help
     */
    public Help() {
        initComponents();
     txtHelp.setText(
        "SUNRISE DENTAL CLINIC\n"
        + "USER GUIDE\n"
        + "========================================\n\n"

        + "1. LOGIN\n"
        + "Enter your authorized username and password.\n"
        + "Click Login to access the system.\n\n"

        + "2. REGISTER PATIENT\n"
        + "Enter the patient's personal information.\n"
        + "Make sure the contact number is correct.\n\n"

        + "3. REGISTER APPOINTMENT\n"
        + "Select the patient, dentist and treatment.\n"
        + "Enter the appointment date and time.\n"
        + "The system automatically calculates the bill.\n"
        + "The system prevents dentist double bookings.\n\n"

        + "4. SEARCH APPOINTMENT\n"
        + "Enter the appointment number and click Search.\n"
        + "The complete appointment information will be displayed.\n\n"

        + "5. BILLING\n"
        + "Search for the appointment.\n"
        + "Check the consultation and treatment fees.\n"
        + "Click Calculate to display the total.\n"
        + "Click Print to print the patient receipt.\n\n"

        + "6. DENTIST MANAGEMENT\n"
        + "Authorized staff can add and update dentist records.\n"
        + "Inactive dentists cannot be selected for new appointments.\n\n"

        + "7. TREATMENT MANAGEMENT\n"
        + "Authorized staff can add and update treatments.\n"
        + "Treatment costs are used during billing.\n\n"

        + "8. REPORTS\n"
        + "Select a date and generate an appointment report.\n"
        + "Reports show appointments and total revenue.\n"
        + "Reports can be printed for management use.\n\n"

        + "9. LOGOUT\n"
        + "Use Logout when you finish working.\n"
        + "Never leave the system logged in when unattended.\n\n"

        + "10. EXIT\n"
        + "Use Exit to safely close the application.\n\n"

        + "For technical problems, contact the system administrator."
);
    
    ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental2.jpg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel1.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtHelp = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHelp.setEditable(false);
        txtHelp.setBackground(new java.awt.Color(204, 255, 204));
        txtHelp.setColumns(20);
        txtHelp.setLineWrap(true);
        txtHelp.setRows(5);
        txtHelp.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtHelp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 21, 852, 490));

        btnClose.setBackground(new java.awt.Color(255, 153, 153));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 546, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
            dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtHelp;
    // End of variables declaration//GEN-END:variables
}
