/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Vikasitha
 */
public class PatientManagement extends javax.swing.JFrame {

    /**
     * Creates new form PatientManagement
     */
    public PatientManagement() {
        initComponents();
         loadPatients();
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental2.jpg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel8.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private void clearForm() {

    txtPatientName.setText("");
    txtAddress.setText("");
    txtContact.setText("");
    txtEmail.setText("");
    txtDateOfBirth.setText("");

    cmbGender.setSelectedIndex(0);

    txtPatientName.requestFocus();
}
    
    private void loadPatients() {

    dao.PatientDAO patientDAO = new dao.PatientDAO();

    java.util.List<model.Patient> patients =
            patientDAO.getAllPatients();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
                    tblPatients.getModel();

    model.setRowCount(0);

    for (model.Patient patient : patients) {

        model.addRow(new Object[]{
            patient.getPatientId(),
            patient.getPatientName(),
            patient.getAddress(),
            patient.getContactNumber(),
            patient.getEmail(),
            patient.getDateOfBirth(),
            patient.getGender()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        txtAddress = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDateOfBirth = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patients");
        setPreferredSize(new java.awt.Dimension(1070, 600));
        setSize(new java.awt.Dimension(1070, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Patient Name :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 76, 112, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Patients Registration");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 6, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Address :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 116, 112, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Contact Number :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 156, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 196, 112, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Date of Birth :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 236, 112, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Gender :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 276, 112, -1));
        getContentPane().add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 76, 282, -1));
        getContentPane().add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 116, 282, -1));
        getContentPane().add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 156, 282, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 196, 282, -1));
        getContentPane().add(txtDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 236, 282, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Male", "Female", " " }));
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 276, 282, -1));

        btnSave.setBackground(new java.awt.Color(204, 255, 204));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 342, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 204, 204));
        btnClear.setText("CLEAR");
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 342, -1, -1));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Patient Name", "Address", "Contact", "Email", "DOB", "Gender"
            }
        ));
        jScrollPane1.setViewportView(tblPatients);
        if (tblPatients.getColumnModel().getColumnCount() > 0) {
            tblPatients.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 76, 570, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental2.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1070, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String name = txtPatientName.getText().trim();
    String address = txtAddress.getText().trim();
    String contact = txtContact.getText().trim();
    String email = txtEmail.getText().trim();
    String dob = txtDateOfBirth.getText().trim();

    String gender = cmbGender.getSelectedItem().toString();

    if (name.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the patient name.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtPatientName.requestFocus();
        return;
    }

    if (contact.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the contact number.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtContact.requestFocus();
        return;
    }

    if (!contact.matches("\\d{10}")) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Contact number must contain 10 digits.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtContact.requestFocus();
        return;
    }

    model.Patient patient = new model.Patient();

    patient.setPatientName(name);
    patient.setAddress(address);
    patient.setContactNumber(contact);
    patient.setEmail(email);
    patient.setDateOfBirth(dob);
    patient.setGender(gender);

    dao.PatientDAO patientDAO = new dao.PatientDAO();

    boolean success = patientDAO.addPatient(patient);

    if (success) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Patient registered successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
        loadPatients();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to register patient.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblPatients;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDateOfBirth;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
