/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import java.awt.Image;
/**
 *
 * @author Vikasitha
 */
public class RegisterAppointment extends javax.swing.JFrame {

    /**
     * Creates new form RegisterAppointment
     */
    public RegisterAppointment() {
        initComponents();
            loadAppointmentNumber();
    loadPatients();
    loadDentists();
    loadTreatments();

    txtAppointmentNumber.setEditable(false);
    txtTreatmentCost.setEditable(false);
    txtTotal.setEditable(false);
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental6.jpeg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel11.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private void loadAppointmentNumber() {

    dao.AppointmentDAO dao =
            new dao.AppointmentDAO();

    txtAppointmentNumber.setText(
            dao.generateAppointmentNumber()
    );
}
    
    private void loadPatients() {

    try {

        dao.PatientDAO patientDAO =
                new dao.PatientDAO();

        java.sql.ResultSet rs =
                patientDAO.getPatientNames();

        cmbPatient.removeAllItems();

        while (rs != null && rs.next()) {

            cmbPatient.addItem(
                    rs.getInt("patient_id")
                    + " - "
                    + rs.getString("patient_name")
            );
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to load patients.\n"
                + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    private void loadDentists() {

    try {

        dao.DentistDAO dentistDAO =
                new dao.DentistDAO();

        java.sql.ResultSet rs =
                dentistDAO.getAllDentists();

        cmbDentist.removeAllItems();

        while (rs != null && rs.next()) {

            cmbDentist.addItem(
                    rs.getInt("dentist_id")
                    + " - "
                    + rs.getString("dentist_name")
            );
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to load dentists.\n"
                + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    private void loadTreatments() {

    try {

        dao.TreatmentDAO treatmentDAO =
                new dao.TreatmentDAO();

        java.sql.ResultSet rs =
                treatmentDAO.getAllTreatments();

        cmbTreatment.removeAllItems();

        while (rs != null && rs.next()) {

            cmbTreatment.addItem(
                    rs.getInt("treatment_id")
                    + " - "
                    + rs.getString("treatment_name")
                    + " - Rs. "
                    + rs.getDouble("treatment_cost")
            );
        }

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to load treatments.\n"
                + e.getMessage(),
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
}
    
    private void clearAppointmentForm() {

    cmbPatient.setSelectedIndex(-1);
    cmbDentist.setSelectedIndex(-1);
    cmbTreatment.setSelectedIndex(-1);

    txtAppointmentDate.setText("");
    txtAppointmentTime.setText("");

    txtConsultationFee.setText("2500.00");
    txtTreatmentCost.setText("0.00");
    txtTotal.setText("0.00");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtAppointmentNumber = new javax.swing.JTextField();
        cmbPatient = new javax.swing.JComboBox<>();
        cmbDentist = new javax.swing.JComboBox<>();
        cmbTreatment = new javax.swing.JComboBox<>();
        txtAppointmentDate = new javax.swing.JTextField();
        txtAppointmentTime = new javax.swing.JTextField();
        txtConsultationFee = new javax.swing.JTextField();
        txtTreatmentCost = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Appionment");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Register New Appoinment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 45, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Appoinment No :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 114, 136, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Patient :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 155, 136, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Dentist :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 202, 136, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Treatment :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 246, 136, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Appointment Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 290, 136, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Appointment Time :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 331, 136, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Consultation :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 378, 136, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Treatment Cost :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 422, 136, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Total :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 466, 136, -1));

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 543, -1, -1));

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 543, -1, -1));

        txtAppointmentNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAppointmentNumber.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(txtAppointmentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 111, 306, -1));

        cmbPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Patient" }));
        getContentPane().add(cmbPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 155, 306, -1));

        cmbDentist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbDentist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Dentist" }));
        getContentPane().add(cmbDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 199, 306, -1));

        cmbTreatment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbTreatment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Treatment" }));
        cmbTreatment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTreatmentActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 243, 306, -1));

        txtAppointmentDate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 287, 306, -1));

        txtAppointmentTime.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtAppointmentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 331, 306, -1));

        txtConsultationFee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtConsultationFee.setText("2500.00");
        txtConsultationFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultationFeeActionPerformed(evt);
            }
        });
        getContentPane().add(txtConsultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 375, 306, -1));

        txtTreatmentCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTreatmentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 419, 306, -1));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 463, 306, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental6.jpeg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -4, 1070, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTreatmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTreatmentActionPerformed
        // TODO add your handling code here:
        if (cmbTreatment.getSelectedItem() == null) {
        return;
    }

    String selected =
            cmbTreatment.getSelectedItem().toString();

    try {

        String[] parts = selected.split(" - ");

        double cost = Double.parseDouble(
                parts[parts.length - 1]
                        .replace("Rs.", "")
                        .trim()
        );

        txtTreatmentCost.setText(
                String.format("%.2f", cost)
        );

        calculateTotal();

    } catch (Exception e) {

        txtTreatmentCost.setText("0.00");
        txtTotal.setText("0.00");
    }
    }//GEN-LAST:event_cmbTreatmentActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (cmbPatient.getSelectedItem() == null
            || cmbDentist.getSelectedItem() == null
            || cmbTreatment.getSelectedItem() == null) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select patient, dentist and treatment.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String date =
            txtAppointmentDate.getText().trim();

    String time =
            txtAppointmentTime.getText().trim();

    if (date.isEmpty() || time.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter appointment date and time.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        String patientText =
                cmbPatient.getSelectedItem().toString();

        String dentistText =
                cmbDentist.getSelectedItem().toString();

        String treatmentText =
                cmbTreatment.getSelectedItem().toString();

        int patientId = Integer.parseInt(
                patientText.split(" - ")[0]
        );

        int dentistId = Integer.parseInt(
                dentistText.split(" - ")[0]
        );

        int treatmentId = Integer.parseInt(
                treatmentText.split(" - ")[0]
        );

        // Validate date
        java.sql.Date.valueOf(date);

        // Validate time
        java.sql.Time.valueOf(time + ":00");

        dao.AppointmentDAO appointmentDAO =
                new dao.AppointmentDAO();

        // Prevent double booking
        if (!appointmentDAO.isDentistAvailable(
                dentistId,
                date,
                time + ":00")) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "This dentist already has an appointment "
                    + "at the selected date and time.\n\n"
                    + "Please select another time.",
                    "Double Booking",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        double consultationFee =
                Double.parseDouble(
                        txtConsultationFee.getText().trim()
                );

        double treatmentCost =
                Double.parseDouble(
                        txtTreatmentCost.getText().trim()
                );

        double total =
                consultationFee + treatmentCost;

        model.Appointment appointment =
                new model.Appointment();

        appointment.setAppointmentNumber(
                txtAppointmentNumber.getText()
        );

        appointment.setPatientId(patientId);
        appointment.setDentistId(dentistId);
        appointment.setTreatmentId(treatmentId);
        appointment.setAppointmentDate(date);
        appointment.setAppointmentTime(time + ":00");
        appointment.setStatus("CONFIRMED");
        appointment.setConsultationFee(consultationFee);
        appointment.setTotalAmount(total);

        boolean success =
                appointmentDAO.addAppointment(appointment);

        if (success) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Appointment registered successfully!\n\n"
                    + "Appointment No: "
                    + appointment.getAppointmentNumber()
                    + "\nTotal: Rs. "
                    + String.format("%.2f", total),
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            clearAppointmentForm();

            loadAppointmentNumber();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Unable to save appointment.",
                    "Database Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }

    } catch (IllegalArgumentException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid date or time format.\n\n"
                + "Date: YYYY-MM-DD\n"
                + "Time: HH:MM",
                "Invalid Input",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Error: " + e.getMessage(),
                "System Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         cmbPatient.setSelectedIndex(-1);
    cmbDentist.setSelectedIndex(-1);
    cmbTreatment.setSelectedIndex(-1);

    txtAppointmentDate.setText("");
    txtAppointmentTime.setText("");

    txtConsultationFee.setText("2500.00");
    txtTreatmentCost.setText("0.00");
    txtTotal.setText("0.00");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtConsultationFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultationFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultationFeeActionPerformed
    
    private void calculateTotal() {

    try {

        double consultation =
                Double.parseDouble(
                        txtConsultationFee.getText().trim()
                );

        double treatment =
                Double.parseDouble(
                        txtTreatmentCost.getText().trim()
                );

        double total = consultation + treatment;

        txtTotal.setText(
                String.format("%.2f", total)
        );

    } catch (NumberFormatException e) {

        txtTotal.setText("0.00");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDentist;
    private javax.swing.JComboBox<String> cmbPatient;
    private javax.swing.JComboBox<String> cmbTreatment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAppointmentDate;
    private javax.swing.JTextField txtAppointmentNumber;
    private javax.swing.JTextField txtAppointmentTime;
    private javax.swing.JTextField txtConsultationFee;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTreatmentCost;
    // End of variables declaration//GEN-END:variables
}
