/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Vikasitha
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
    initComponents();
    
    ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental11.jpeg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060, 610, Image.SCALE_SMOOTH);
    jLabel7.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private String tblReportsToText() {

    StringBuilder text =
            new StringBuilder();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
                    tblReports.getModel();

    for (int row = 0;
         row < model.getRowCount();
         row++) {

        for (int column = 0;
             column < model.getColumnCount();
             column++) {

            text.append(
                    model.getValueAt(row, column)
            );

            text.append(" | ");
        }

        text.append("\n");
    }

    return text.toString();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbReportType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtReportDate = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTotalAppointments = new javax.swing.JTextField();
        lblTotalRevenue = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Sunrise Dental Clinic");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 15, 355, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Management Reports");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 69, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Report  Type :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 143, -1, -1));

        cmbReportType.setBackground(new java.awt.Color(204, 255, 255));
        cmbReportType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appointment Report", "Revenue Report", "Dentist Report", "Treatment Report" }));
        getContentPane().add(cmbReportType, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 140, 447, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 187, 96, -1));

        txtReportDate.setBackground(new java.awt.Color(204, 255, 255));
        txtReportDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtReportDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 184, 277, -1));

        btnGenerate.setBackground(new java.awt.Color(204, 255, 204));
        btnGenerate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerate.setText("GENERATE REPORT");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 184, -1, -1));

        tblReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment No", "Patient", "Dentist", "Treatment", "Date ", "Time", "Status", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 223, 799, 183));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Total Appointments :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 438, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Total Revenue :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 476, 160, -1));

        btnPrint.setBackground(new java.awt.Color(153, 153, 255));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setText("PRINT REPORT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 540, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 204, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 540, 146, -1));

        lblTotalAppointments.setBackground(new java.awt.Color(204, 255, 255));
        lblTotalAppointments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lblTotalAppointments, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 438, 415, -1));

        lblTotalRevenue.setBackground(new java.awt.Color(204, 255, 255));
        lblTotalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lblTotalRevenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 482, 415, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental11.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        // TODO add your handling code here:
            String date =
            txtReportDate.getText().trim();

    if (date.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter a date.",
                "Input Required",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    try {

        java.sql.Date.valueOf(date);

    } catch (IllegalArgumentException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the date in this format:\n"
                + "YYYY-MM-DD",
                "Invalid Date",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    dao.ReportDAO reportDAO =
            new dao.ReportDAO();

    try {

        java.sql.ResultSet rs =
                reportDAO.getAppointmentsByDate(date);

        javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel)
                        tblReports.getModel();

        model.setRowCount(0);

        while (rs != null && rs.next()) {

            model.addRow(new Object[]{

                rs.getString("appointment_number"),

                rs.getString("patient_name"),

                rs.getString("dentist_name"),

                rs.getString("treatment_name"),

                rs.getDate("appointment_date"),

                rs.getTime("appointment_time"),

                rs.getString("status"),

                String.format(
                        "Rs. %.2f",
                        rs.getDouble("total_amount")
                )
            });
        }

        int count =
                reportDAO.getAppointmentCount(date);

        double revenue =
                reportDAO.getRevenueByDate(date);

        lblTotalAppointments.setText(
                "Total Appointments: " + count
        );

        lblTotalRevenue.setText(
                String.format(
                        "Total Revenue: Rs. %.2f",
                        revenue
                )
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to generate report.",
                "Report Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
            try {

        javax.swing.JTextArea report =
                new javax.swing.JTextArea();

        report.setText(
            "       SUNRISE DENTAL CLINIC\n"
            + "          APPOINTMENT REPORT\n"
            + "====================================\n\n"
            + txtReportDate.getText()
            + "\n\n"
            + tblReportsToText()
            + "\n\n"
            + lblTotalAppointments.getText()
            + "\n"
            + lblTotalRevenue.getText()
        );

        report.setFont(
            new java.awt.Font(
                "Monospaced",
                java.awt.Font.PLAIN,
                10
            )
        );

        report.print();

    } catch (java.awt.print.PrinterException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to print report.",
                "Print Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
           // Clear date field
    txtReportDate.setText("");

    // Clear report table
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblReports.getModel();

    model.setRowCount(0);

    // Reset summary labels
    lblTotalAppointments.setText("Total Appointments: 0");
    lblTotalRevenue.setText("Total Revenue: Rs. 0.00");

    // Reset report type
    cmbReportType.setSelectedIndex(0);

    // Put cursor back in date field
    txtReportDate.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cmbReportType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblTotalAppointments;
    private javax.swing.JTextField lblTotalRevenue;
    private javax.swing.JTable tblReports;
    private javax.swing.JTextField txtReportDate;
    // End of variables declaration//GEN-END:variables
}
