/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author Vikasitha
 */
public class TreatmentManagement extends javax.swing.JFrame {

    /**
     * Creates new form TreatmentManagement
     */
    public TreatmentManagement() {
        initComponents();
         loadTreatments();
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/view/dental10.jpeg"));
    Image scaledImage = originalIcon.getImage().getScaledInstance(1060,610, Image.SCALE_SMOOTH);
    jLabel5.setIcon(new ImageIcon(scaledImage));
    
    setResizable(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    private void loadTreatments() {

    dao.TreatmentDAO treatmentDAO =
            new dao.TreatmentDAO();

    java.util.List<model.Treatment> treatments =
            treatmentDAO.getAllTreatmentsList();

    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel)
                    tblTreatments.getModel();

    model.setRowCount(0);

    for (model.Treatment treatment : treatments) {

        model.addRow(new Object[]{
            treatment.getTreatmentId(),
            treatment.getTreatmentName(),
            String.format(
                    "Rs. %.2f",
                    treatment.getTreatmentCost()
            ),
            treatment.getStatus()
        });
    }
}
    
    private void clearForm() {

    txtTreatmentName.setText("");
    txtTreatmentCost.setText("");

    cmbStatus.setSelectedIndex(0);

    txtTreatmentName.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTreatmentName = new javax.swing.JTextField();
        txtTreatmentCost = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTreatments = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Treatment Management");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Treatment Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 26, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Treatement Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 125, 155, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Treatment Cost :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 169, 155, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Status :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 238, 155, -1));

        txtTreatmentName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTreatmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 122, 326, -1));

        txtTreatmentCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtTreatmentCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 166, 326, -1));

        cmbStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbStatus.setForeground(new java.awt.Color(51, 0, 255));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "INACTIVE" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 235, 326, -1));

        btnSave.setBackground(new java.awt.Color(153, 255, 153));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 297, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(153, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 297, -1, -1));

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 297, -1, -1));

        tblTreatments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Treatment Name", "Cost", "Status"
            }
        ));
        tblTreatments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTreatmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTreatments);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 351, 903, 162));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/dental10.jpeg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1060, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
            String name =
            txtTreatmentName.getText().trim();

    String costText =
            txtTreatmentCost.getText().trim();

    String status =
            cmbStatus.getSelectedItem().toString();

    if (name.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the treatment name.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtTreatmentName.requestFocus();
        return;
    }

    if (costText.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter the treatment cost.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtTreatmentCost.requestFocus();
        return;
    }

    double cost;

    try {

        cost = Double.parseDouble(costText);

        if (cost < 0) {
            throw new NumberFormatException();
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter a valid treatment cost.",
                "Invalid Cost",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        txtTreatmentCost.requestFocus();
        return;
    }

    model.Treatment treatment =
            new model.Treatment();

    treatment.setTreatmentName(name);
    treatment.setTreatmentCost(cost);
    treatment.setStatus(status);

    dao.TreatmentDAO treatmentDAO =
            new dao.TreatmentDAO();

    if (treatmentDAO.addTreatment(treatment)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Treatment added successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
        loadTreatments();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to add treatment.",
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
          clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblTreatmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTreatmentsMouseClicked
        // TODO add your handling code here:
            int row =
            tblTreatments.getSelectedRow();

    if (row >= 0) {

        txtTreatmentName.setText(
                tblTreatments
                        .getValueAt(row, 1)
                        .toString()
        );

        String cost =
                tblTreatments
                        .getValueAt(row, 2)
                        .toString()
                        .replace("Rs.", "")
                        .trim();

        txtTreatmentCost.setText(cost);

        cmbStatus.setSelectedItem(
                tblTreatments
                        .getValueAt(row, 3)
                        .toString()
        );
    }
    }//GEN-LAST:event_tblTreatmentsMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
            int row =
            tblTreatments.getSelectedRow();

    if (row == -1) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please select a treatment from the table.",
                "Selection Required",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    int treatmentId =
            Integer.parseInt(
                    tblTreatments
                            .getValueAt(row, 0)
                            .toString()
            );

    String name =
            txtTreatmentName.getText().trim();

    String costText =
            txtTreatmentCost.getText().trim();

    if (name.isEmpty() || costText.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please complete all required fields.",
                "Validation Error",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    double cost;

    try {

        cost = Double.parseDouble(costText);

        if (cost < 0) {
            throw new NumberFormatException();
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Please enter a valid treatment cost.",
                "Invalid Cost",
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        return;
    }

    String status =
            cmbStatus.getSelectedItem().toString();

    model.Treatment treatment =
            new model.Treatment();

    treatment.setTreatmentId(treatmentId);
    treatment.setTreatmentName(name);
    treatment.setTreatmentCost(cost);
    treatment.setStatus(status);

    dao.TreatmentDAO treatmentDAO =
            new dao.TreatmentDAO();

    if (treatmentDAO.updateTreatment(treatment)) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Treatment updated successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        clearForm();
        loadTreatments();

    } else {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Unable to update treatment.",
                "Database Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreatmentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreatmentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreatmentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreatmentManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreatmentManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTreatments;
    private javax.swing.JTextField txtTreatmentCost;
    private javax.swing.JTextField txtTreatmentName;
    // End of variables declaration//GEN-END:variables
}
